<?php
	DEFINE('DIR_APPCORE',"/admin/appcore");
	DEFINE('DIR_ADMIN','/admin');
	DEFINE('DIR_REQUEST_HANDLERS',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE.'/api_handles//');
	DEFINE('AUTH_SESSION_CHECK','id name logged-in');

	DEFINE('DB_NAME','spywarrior');
	DEFINE('DB_ADDR','35.188.80.186');
	DEFINE('DB_USERNAME','root');
	DEFINE('DB_PASSWORD','GodIsOne');

	DEFINE('FILE_UPLOADER',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/file_uploader.php");
	DEFINE('CLIENT_HANDLER',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/auth/user.php");
	DEFINE('CLIENT_COMMONS',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/commons.php");
	DEFINE('DB_HANDLER',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/db/core.php");
	DEFINE('MAILER',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/mailer/mailer.php");

	//Request Handlers
	DEFINE('RH_PRAYER_REQUEST',DIR_REQUEST_HANDLERS."rh_prayer_request.php");
	DEFINE('RH_LISTINGS',DIR_REQUEST_HANDLERS."rh_listings.php");
	DEFINE('RH_MINI_GALLERY', DIR_REQUEST_HANDLERS."rh_mini_gallery.php");
	DEFINE('RH_MOVIES', DIR_REQUEST_HANDLERS."rh_movies.php");
	DEFINE('RH_COMMENTS', DIR_REQUEST_HANDLERS."rh_comments.php");
	DEFINE('RH_EVENTS', DIR_REQUEST_HANDLERS."rh_events.php");

	DEFINE('CMS_HOME',$_SERVER['DOCUMENT_ROOT'].DIR_ADMIN."/cms.php");

	//Storage
	DEFINE('STORAGE_MUSIC',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/storage/music/");
	DEFINE('STORAGE_MOVIES',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/storage/movies/");
	DEFINE('STORAGE_EVENTS',$_SERVER['DOCUMENT_ROOT'].DIR_APPCORE."/storage/events/");
?>